# Copyright ZeroX.

# Global define (Required)
global:
  # Full name override
  fullname: "mysql"
  # Name override
  name: "mysql"
  # Kube version
  kubeVersion: ""

# Primary
primary:
  # The name of the MySQL primary replica
  name: mysql-primary

# Backup
backup:
  enabled: false
